/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogotecprog;

import dao.SaveLoad;
import javax.swing.JLabel;

/**
 *
 * @author risad
 */
public class Menu extends javax.swing.JFrame {

    private Controle contr;

    public Menu() {

        initComponents();

    }

    NomeDuo janela2 = new NomeDuo();

    void enviaPalavras(Controle c) {
        contr = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoJogar = new javax.swing.JButton();
        botaoCarregar = new javax.swing.JButton();
        botaoRecorde = new javax.swing.JButton();
        botaoCarregar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoJogar.setText("Jogar");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        botaoCarregar.setText("Carregar TXT");
        botaoCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregarActionPerformed(evt);
            }
        });

        botaoRecorde.setText("Recordes");
        botaoRecorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecordeActionPerformed(evt);
            }
        });

        botaoCarregar2.setText("Carregar CSV");
        botaoCarregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarregar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(botaoJogar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCarregar2)
                            .addComponent(botaoCarregar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(botaoRecorde)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botaoJogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCarregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCarregar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRecorde)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed

        if (janela2 == null) {
            janela2 = new NomeDuo();
            janela2.setVisible(true);
        } else {
            janela2.setVisible(true);
        }
        janela2.enviaControle(contr);
        this.setVisible(false);


    }//GEN-LAST:event_botaoJogarActionPerformed

    private void botaoCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregarActionPerformed
        //ler arquivo

        String nomeJog1 = null, nomeJog2 = null;
        int vidaJog1 = 0, vidaJog2 = 0, fase = 0;

        String linhas[] = new String[5];

        SaveLoad carregarTxt = new SaveLoad();
        linhas = carregarTxt.carregar("save.txt");
        /*a lista de strings linhas recebe a lista de strings que o metodo
        carregar retorna*/

        nomeJog1 = linhas[0];
        nomeJog2 = linhas[1];
        vidaJog1 = Integer.parseInt(linhas[2]);
        vidaJog2 = Integer.parseInt(linhas[3]);
        fase = Integer.parseInt(linhas[4]);

        /*passando esses dados salvo para comecar o jogo com eles */
        contr.setNomeDuo(nomeJog1, nomeJog2, fase, vidaJog1, vidaJog2);
        contr.comecaJogo();
        this.setVisible(false);

    }//GEN-LAST:event_botaoCarregarActionPerformed

    private void botaoCarregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarregar2ActionPerformed
        //ler arquivo

        String nomeJog1 = null, nomeJog2 = null;
        int vidaJog1 = 0, vidaJog2 = 0, fase = 0;

        String linhas[] = new String[5];

        SaveLoad carregarTxt = new SaveLoad();
        linhas = carregarTxt.carregar("save.csv");
        /*a lista de strings linhas recebe a lista de strings que o metodo
        carregar retorna*/

        nomeJog1 = linhas[0];
        nomeJog2 = linhas[1];
        vidaJog1 = Integer.parseInt(linhas[2]);
        vidaJog2 = Integer.parseInt(linhas[3]);
        fase = Integer.parseInt(linhas[4]);

        /*passando esses dados salvo para comecar o jogo com eles */
        contr.setNomeDuo(nomeJog1, nomeJog2, fase, vidaJog1, vidaJog2);
        contr.comecaJogo();
        this.setVisible(false);
    }//GEN-LAST:event_botaoCarregar2ActionPerformed

    private void botaoRecordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecordeActionPerformed
        String linhas[] = new String[100];

        SaveLoad carregarRecorde = new SaveLoad();
        linhas = carregarRecorde.carregarRecordes("recorde.txt");
        //linhas = carregarRecorde.carregarRecordes("recorde.csv");

        /*a lista de strings linhas recebe a lista de strings que o metodo
        carregarRecordes retorna*/
        String recorde = "";

        Recordes janelaRecordes = new Recordes();
        janelaRecordes.setVisible(true);
        janelaRecordes.setSize(600, 500);
        janelaRecordes.setResizable(false);

        for (int c = 0; c < 100; c++) {
            if (linhas[c] != null) {
                recorde = linhas[c];
                janelaRecordes.getTabela().setValueAt(recorde, c, 0);
            }
        }

    }//GEN-LAST:event_botaoRecordeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCarregar;
    private javax.swing.JButton botaoCarregar2;
    private javax.swing.JButton botaoJogar;
    private javax.swing.JButton botaoRecorde;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
